# This is an example how to use the key schema_filter

# if you have one database connection
doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    schema_filter: ~(?<!_version)$~

  orm:
  # other stuff here

# if you have multiple database connections
doctrine:
  dbal:
    # configure these for your database server
    default_connection: default
    connections:
      default:
        # first Connection
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        schema_filter: ~(?<!_version)$~
        logging: false
      second:
        # second Connection
        url: '%env(resolve:DATABASE_SECOND_URL)%'
        driver: 'pdo_mysql'
        schema_filter: ~(?<!_version)$~
  orm:
    # other stuff here
