netbrothers_version:
  ignore_tables: # these tables will be ignored
    ['doctrine_migration_versions']
  ignore_columns: # these columns will not be compared
    ['id', 'version', 'created_at', 'updated_at']
