netbrothers_version:
  ignore_tables: # this tables will be ignored
    ['doctrine_migration_versions']
  ignore_columns: # this columns will not be compare
    ['id', 'version', 'created_at', 'updated_at']